defaults: &defaults
  access_key: 'YxQM2umRtzrlXuzaxGccC-7UJbdwwD2BUGXO9ufo'
  secret_key: 'u0UKs-SHXd6xehQKrOp-YNDtxOP8FQsHZ3n4sMIR'
  bucket_pictures: 'wp-img-asset'
  bucket_media: 'wp-media-asset'
  bucket_views720: 'wp-media-asset'
  bucket_wmall: 'wp-img-asset'
  domain: 'wechatplus.getstore.cn'
  domain_old: 'qiniucdn.com'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
