common: &common
  hostname: "wx.winwemedia.com"
  mhostname: "m.wx.winwemedia.com"
  hotelhostname: "hotel.winwemedia.com"
  sms_service: 'zhilian'
  zhilian_url: 'http://61.145.229.29:9003/MWGate/wmgw.asmx'
  zhilian_user_id: 'J02110'
  zhilian_password: '696896'
  uploads_dir: <%= "#{Rails.root}/public/uploads" %>
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://ui.m.wx.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://ui.m.wx.winwemedia.com/yeepay/callback'
  wx_plugin:
    token: 60a485936f65c1319fc5737fb6e000ad
    base64_aes_key: vcl68a4506e798ce30e2c36714f5d1bcae748b6f482
    component_app_id: wx0dd374bc7244fb86
    component_app_secret: 0c79e1fa963cd80cc0be99b20a18faeb
    encoding_aes_key: vcl68a4506e798ce30e2c36714f5d1bcae748b6f482

production:
  <<: *common
  hostname: "wx.winwemedia.com"
  mhostname: "m.winwemedia.com"
  hotelhostname: "hotel.winwemedia.com"
  uploads_dir: "/opt/apps/shared/winwemedia/uploads"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://wx.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://wx.winwemedia.com/yeepay/callback'

staging:
  <<: *common
  hostname: "staging.winwemedia.com"
  mhostname: "staging.m.wx.winwemedia.com"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://staging.m.wx.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://staging.m.wx.winwemedia.com/yeepay/callback'

development:
  <<: *common
  hostname: "winwemedia.dev:3000"
  mhostname: "m.winwemedia.dev:3000"

test:
  <<: *common
