common: &common
  hostname: "m.mpp.getstore.cn"
  mhostname: "m.mpp.getstore.cn"
  wshop_host:     "http://ec.mpp.getstore.cn"
  wmall_host:     "http://wmall.mpp.getstore.cn"
  wlife_host:     "http://wlife.mpp.getstore.cn"
  shequ_host:     "http://shequ.mpp.getstore.cn"
  hotel_host:     "http://hotel.mpp.getstore.cn"
  recommend_host: "http://recommend.mpp.getstore.cn"
  oa_host:        "http://oa.mpp.getstore.cn"
  faye_host:      "http://localhost:9393"
  app_host: "http://api.mpp.getstore.cn"
  wxapi_host: "http://api.wx.mpp.getstore.cn"
  cas_url: "http://127.0.0.1:8001"
  sms_service: 'zhilian'
  zhilian_url: 'http://61.145.229.29:9003/MWGate/wmgw.asmx'
  zhilian_user_id: 'J02110'
  zhilian_password: '696896'
  uploads_dir: <%= "#{Rails.root}/public/uploads" %>
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://ui.m.mpp.getstore.cn/yeepay/callback"
    fcallbackurl: 'http://ui.m.mpp.getstore.cn/yeepay/callback'
  wx_plugin:
    token: <%= Rails.application.secrets.wx_open['token'] %>
    encoding_aes_key: <%= Rails.application.secrets.wx_open['encoding_aes_key'] %>
    component_app_id: <%= Rails.application.secrets.wx_open['component_app_id'] %>
    component_app_secret: <%= Rails.application.secrets.wx_open['component_app_secret'] %>

production:
  <<: *common
  hostname: "m.mpp.getstore.cn"
  mhostname: "m.mpp.getstore.cn"
  wshop_host:     "http://ec.mpp.getstore.cn"
  wmall_host:     "http://mall.mpp.getstore.cn"
  wlife_host:     "http://life.mpp.getstore.cn"
  shequ_host:     "http://shequ.mpp.getstore.cn"
  hotel_host:     "http://hotel.mpp.getstore.cn"
  oa_host:        "http://oa.mpp.getstore.cn"
  recommend_host: "http://lifeboat.mpp.getstore.cn"
  faye_host:      "http://faye.api.mpp.getstore.cn:9393"
  app_host:       "http://api.mpp.getstore.cn"
  wxapi_host: "http://api.wx.mpp.getstore.cn"
  cas_url:        "http://cas.mpp.getstore.cn"
  uploads_dir:    "/opt/apps/shared/51wei/uploads"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://m.mpp.getstore.cn/yeepay/callback"
    fcallbackurl: 'http://m.mpp.getstore.cn/yeepay/callback'
  wx_plugin:
    token: <%= Rails.application.secrets.wx_open['token'] %>
    encoding_aes_key: <%= Rails.application.secrets.wx_open['encoding_aes_key'] %>
    component_app_id: <%= Rails.application.secrets.wx_open['component_app_id'] %>
    component_app_secret: <%= Rails.application.secrets.wx_open['component_app_secret'] %>

staging:
  <<: *common
  hostname: "staging.mpp.getstore.cn"
  mhostname: "stagingm.mpp.getstore.cn"
  wshop_host:     "http://staging.ec.mpp.getstore.cn"
  wmall_host:     "http://staging.mall.mpp.getstore.cn"
  wlife_host:     "http://wlife.mpp.getstore.cn"
  shequ_host:     "http://staging.shequ.mpp.getstore.cn"
  hotel_host:     "http://staging.mpp.getstore.cn"
  oa_host:        "http://staging.mpp.getstore.cn"
  recommend_host: "http://staging.mpp.getstore.cn"
  app_host: "http://staging.mpp.getstore.cn"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://staging.m.mpp.getstore.cn/yeepay/callback"
    fcallbackurl: 'http://staging.m.mpp.getstore.cn/yeepay/callback'

development:
  <<: *common
  hostname: "testwx.getstore.cn"
  mhostname: "m.testwx.getstore.cn"
  wshop_host:     "http://127.0.0.1:3003"
  wmall_host:     "http://127.0.0.1:3002"
  wlife_host:     "http://127.0.0.1:3001"
  shequ_host:     "http://127.0.0.1:3004"
  recommend_host: "http://127.0.0.1:3005"
  app_host:       "http://127.0.0.1:3006"

test:
  <<: *common
