common: &common
  hostname: "m.wp.ruanshan.com"
  mhostname: "m.wp.ruanshan.com"
  wshop_host:     "http://ec.wp.ruanshan.com"
  wmall_host:     "http://wmall.wp.ruanshan.com"
  wlife_host:     "http://wlife.wp.ruanshan.com"
  shequ_host:     "http://shequ.wp.ruanshan.com"
  hotel_host:     "http://hotel.wp.ruanshan.com"
  recommend_host: "http://recommend.wp.ruanshan.com"
  oa_host:        "http://oa.wp.ruanshan.com"
  faye_host:      "http://localhost:9393"
  app_host: "http://api.wp.ruanshan.com"
  wxapi_host: "http://api.wx.wp.ruanshan.com"
  cas_url: "http://127.0.0.1:8001"
  sms_service: 'zhilian'
  zhilian_url: 'http://61.145.229.29:9003/MWGate/wmgw.asmx'
  zhilian_user_id: 'J02110'
  zhilian_password: '696896'
  uploads_dir: <%= "#{Rails.root}/public/uploads" %>
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://ui.m.wp.ruanshan.com/yeepay/callback"
    fcallbackurl: 'http://ui.m.wp.ruanshan.com/yeepay/callback'
  wx_plugin:
    token: <%= Rails.application.secrets.wx_open['token'] %>
    base64_aes_key: <%= Rails.application.secrets.wx_open['base64_aes_key'] %>
    encoding_aes_key: <%= Rails.application.secrets.wx_open['encoding_aes_key'] %>
    component_app_id: <%= Rails.application.secrets.wx_open['component_app_id'] %>
    component_app_secret: <%= Rails.application.secrets.wx_open['component_app_secret'] %>

production:
  <<: *common
  hostname: "m.wp.ruanshan.com"
  mhostname: "m.wp.ruanshan.com"
  wshop_host:     "http://ec.wp.ruanshan.com"
  wmall_host:     "http://mall.wp.ruanshan.com"
  wlife_host:     "http://life.wp.ruanshan.com"
  shequ_host:     "http://shequ.wp.ruanshan.com"
  hotel_host:     "http://hotel.wp.ruanshan.com"
  oa_host:        "http://oa.wp.ruanshan.com"
  recommend_host: "http://lifeboat.wp.ruanshan.com"
  faye_host:      "http://faye.api.wp.ruanshan.com:9393"
  app_host:       "http://api.wp.ruanshan.com"
  wxapi_host: "http://api.wx.wp.ruanshan.com"
  cas_url:        "http://cas.wp.ruanshan.com"
  uploads_dir:    "/opt/apps/shared/51wei/uploads"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://m.wp.ruanshan.com/yeepay/callback"
    fcallbackurl: 'http://m.wp.ruanshan.com/yeepay/callback'
  wx_plugin:
    token: <%= Rails.application.secrets.wx_open['token'] %>
    base64_aes_key: <%= Rails.application.secrets.wx_open['base64_aes_key'] %>
    encoding_aes_key: <%= Rails.application.secrets.wx_open['encoding_aes_key'] %>
    component_app_id: <%= Rails.application.secrets.wx_open['component_app_id'] %>
    component_app_secret: <%= Rails.application.secrets.wx_open['component_app_secret'] %>

staging:
  <<: *common
  hostname: "staging.wp.ruanshan.com"
  mhostname: "stagingm.wp.ruanshan.com"
  wshop_host:     "http://staging.ec.wp.ruanshan.com"
  wmall_host:     "http://staging.mall.wp.ruanshan.com"
  wlife_host:     "http://wlife.wp.ruanshan.com"
  shequ_host:     "http://staging.shequ.wp.ruanshan.com"
  hotel_host:     "http://staging.wp.ruanshan.com"
  oa_host:        "http://staging.wp.ruanshan.com"
  recommend_host: "http://staging.wp.ruanshan.com"
  app_host: "http://staging.wp.ruanshan.com"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://staging.m.wp.ruanshan.com/yeepay/callback"
    fcallbackurl: 'http://staging.m.wp.ruanshan.com/yeepay/callback'

development:
  <<: *common
  hostname: "testwx.getstore.cn"
  mhostname: "m.testwx.getstore.cn"
  wshop_host:     "http://127.0.0.1:3003"
  wmall_host:     "http://127.0.0.1:3002"
  wlife_host:     "http://127.0.0.1:3001"
  shequ_host:     "http://127.0.0.1:3004"
  recommend_host: "http://127.0.0.1:3005"
  app_host:       "http://127.0.0.1:3006"

test:
  <<: *common
