common: &common
  hostname: "m.winwemedia.com"
  mhostname: "m.winwemedia.com"
  wshop_host:     "http://ec.winwemedia.com"
  wmall_host:     "http://wmall.winwemedia.com"
  wlife_host:     "http://wlife.winwemedia.com"
  shequ_host:     "http://shequ.winwemedia.com"
  hotel_host:     "http://hotel.winwemedia.com"
  recommend_host: "http://recommend.winwemedia.com"
  oa_host:        "http://oa.winwemedia.com"
  faye_host:      "http://localhost:9393"
  app_host: "http://api.winwemedia.com"
  cas_url: "http://127.0.0.1:8001"
  sms_service: 'zhilian'
  zhilian_url: 'http://61.145.229.29:9003/MWGate/wmgw.asmx'
  zhilian_user_id: 'J02110'
  zhilian_password: '696896'
  uploads_dir: <%= "#{Rails.root}/public/uploads" %>
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://ui.m.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://ui.m.winwemedia.com/yeepay/callback'
  wx_plugin:
    token: 60a485936f65c1319fc5737fb6e000ad
    base64_aes_key: vcl68a4506e798ce30e2c36714f5d1bcae748b6f482
    component_app_id: wx0dd374bc7244fb86
    component_app_secret: 0c79e1fa963cd80cc0be99b20a18faeb
    encoding_aes_key: vcl68a4506e798ce30e2c36714f5d1bcae748b6f482

production:
  <<: *common
  hostname: "m.winwemedia.com"
  mhostname: "m.winwemedia.com"
  wshop_host:     "http://ec.winwemedia.com"
  wmall_host:     "http://mall.winwemedia.com"
  wlife_host:     "http://life.winwemedia.com"
  shequ_host:     "http://shequ.winwemedia.com"
  hotel_host:     "http://hotel.winwemedia.com"
  oa_host:        "http://oa.winwemedia.com"
  recommend_host: "http://lifeboat.winwemedia.com"
  faye_host:      "http://faye.api.winwemedia.com:9393"
  app_host:       "http://api.winwemedia.com"
  cas_url:        "http://cas.winwemedia.com"
  uploads_dir:    "/opt/apps/shared/winwemedia/uploads"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://m.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://m.winwemedia.com/yeepay/callback'

staging:
  <<: *common
  hostname: "staging.winwemedia.com"
  mhostname: "staging.m.winwemedia.com"
  wshop_host:     "http://staging.ec.winwemedia.com"
  wmall_host:     "http://staging.mall.winwemedia.com"
  wlife_host:     "http://wlife.winwemedia.com"
  shequ_host:     "http://staging.shequ.winwemedia.com"
  hotel_host:     "http://staging.winwemedia.com"
  oa_host:        "http://staging.winwemedia.com"
  recommend_host: "http://staging.winwemedia.com"
  app_host: "http://staging.winwemedia.com"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://staging.m.winwemedia.com/yeepay/callback"
    fcallbackurl: 'http://staging.m.winwemedia.com/yeepay/callback'

development:
  <<: *common
  hostname: "winwemedia.dev:3000"
  mhostname: "m.winwemedia.dev:3000"
  wshop_host:     "http://127.0.0.1:3003"
  wmall_host:     "http://127.0.0.1:3002"
  wlife_host:     "http://127.0.0.1:3001"
  shequ_host:     "http://127.0.0.1:3004"
  recommend_host: "http://127.0.0.1:3005"
  app_host:       "http://127.0.0.1:3006"

test:
  <<: *common
